services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8080:8080"

  frontend:
    build:
      context: frontend
    environment:
      - NODE_ENV=test
      - BASE_API_URL=http://api:8080
    ports:
      - "3000:3000"

  proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.ci.conf:/etc/nginx/conf.d/default.conf:ro
