name: Lint Api

on:
  pull_request:
    branches: main
    types: [opened, synchronize]

jobs:
  lint:
    name: Lint Api
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.x

      - name: Verify Go Modules
        run: go mod tidy && git diff --exit-code

      - name: Run Go Vet
        run: go vet ./...

      - name: Run Go Fmt Check (Optional)
        run: test -z "$(gofmt -l .)" || (echo "Code is not formatted! Run 'gofmt -w .'" && exit 1)
