name: Test API

on:
  pull_request:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.x

      - name: Install Dependencies
        run: |
          cd api
          go mod tidy
          go mod download

      - name: Build
        run: |
          cd api
          go build -v ./...

      - name: Run Tests
        run: |
          cd api
          go test -v ./... -cover
