name: Test Compiler

on:
  pull_request:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: compiler

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4

      - name: Install Node (for Prettier)
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Prettier
        run: npm install -g prettier

      - name: Run Tests
        run: rake test
