name: Test E2E

on:
  pull_request:
    branches: main

jobs:
  test:
    name: Test E2E
    timeout-minutes: 15
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tests/e2e

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Install Docker Compose
        run: |
          sudo apt update
          sudo apt install -y docker-compose

      - name: Start Services
        run: docker-compose -f docker-compose.ci.yml up -d
        working-directory: .

      - name: Run Playwright Tests
        run: PLAYWRIGHT_HTML_OPEN=never npx playwright test --reporter=html

      - name: Stop Services
        if: always()
        run: docker-compose -f docker-compose.ci.yml down
        working-directory: .

      - name: Assert Screenshots
        if: success()
        run: |
          if ! git diff --exit-code screenshots; then
            echo "Screenshots have changed. Run tests locally and commit updated images."
            git diff
            exit 1
          fi

          if [[ -n "$(git ls-files --others --exclude-standard screenshots)" ]]; then
            echo "New untracked screenshot files found. Run tests locally and commit them."
            git ls-files --others --exclude-standard screenshots
            exit 1
          fi

      - uses: actions/upload-artifact@v4
        if: !cancelled()
        with:
          name: playwright-report
          path: tests/e2e/playwright-report/
          retention-days: 30
