name: Test NGINX Configs

on:
  pull_request:
    branches: main
    types: [opened, synchronize]

jobs:
  test-nginx:
    name: Validate ${{ matrix.config.label }} Nginx Config
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - key: dev
            label: Dev
          - key: ci
            label: CI
          - key: deploy
            label: Deploy

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Gixy
        run: |
          sudo apt update
          sudo apt install -y python3-pip
          pip3 install gixy

      - name: Run Gixy Security Audit
        run: gixy ${{ github.workspace }}/nginx.${{ matrix.config.key }}.conf
