name: Test Api

on:
  pull_request:
    branches: main
    types: [opened, synchronize]

jobs:
  test:
    name: Test Api
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.x

      - name: Install Dependencies
        run: |
          go mod tidy
          go mod download

      - name: Build
        run: go build -v ./...

      - name: Run Tests
        run: go test -v ./... -cover
